trigger: none
pool: Default
 

steps:
 - task: TerraformInstaller@1
   inputs:
     terraformVersion: '1.16.5'
 - task: TerraformTask@5
   displayName: terraform FMT
   inputs:
     provider: 'azurerm'
     command: 'custom'
     outputTo: 'console'
     customCommand: 'fmt'
     environmentServiceNameAzureRM: 'sep-serviceconection'

 - task: TerraformTask@5
   displayName: terraform init
   inputs:
     provider: 'azurerm'
     command: 'init'
     workingDirectory: '$(System.DefaultWorkingDirectory)/provider.tf'
     backendServiceArm: 'sep-serviceconection'
     backendAzureRmResourceGroupName: 'Ali-test'
     backendAzureRmStorageAccountName: 'nahid0562'
     backendAzureRmContainerName: 'adostatefiles'
     backendAzureRmKey: 'landing-zone.infra.tfstate'
  

 - task: TerraformTask@5
   displayName: terraform validate
   inputs:
     provider: 'azurerm'
     command: 'validate'
  



